"use client";
import { useEffect, useMemo, useState } from "react";
import { supabase } from "../lib/supabase";

type Screen = "home" | "create" | "join" | "lobby" | "game";
type Round = "lobby" | "round_1" | "round_2" | "finished";
type Player = { id: string; display_name: string; joined_at: string; points: number; status: "locked" | "unlocked"; lock_value: number; round_1_done: boolean };
type Room = { id: string; code: string; host_player_id: string | null; round: Round; current_player_id: string | null; last_roll: number | null };
type Event = { id: number; message: string; created_at: string };
const invite = (c: string) => typeof window === "undefined" ? "/" : `${window.location.origin}/?room=${c}`;
const power = (roll: number | null) => roll === 5 ? 5 : roll === 6 ? 10 : 0;

export default function Home() {
  const [screen, setScreen] = useState<Screen>("home"), [name, setName] = useState(""), [code, setCode] = useState(""), [room, setRoom] = useState<Room | null>(null), [player, setPlayer] = useState<string | null>(null), [players, setPlayers] = useState<Player[]>([]), [events, setEvents] = useState<Event[]>([]), [error, setError] = useState(""), [busy, setBusy] = useState(false), [copied, setCopied] = useState(false);
  useEffect(() => { const c = new URLSearchParams(location.search).get("room"); if (c) { setCode(c.toUpperCase()); setScreen("join"); } }, []);
  useEffect(() => { if (!room || !supabase) return; const client = supabase; let active = true; const load = async () => { const [r, p, e] = await Promise.all([client.from("rooms").select("id,code,host_player_id,round,current_player_id,last_roll").eq("id", room.id).single(), client.from("players").select("id,display_name,joined_at,points,status,lock_value,round_1_done").eq("room_id", room.id).order("joined_at"), client.from("game_events").select("id,message,created_at").eq("room_id", room.id).order("created_at", { ascending: false }).limit(30)]); if (!active) return; if (r.data) { setRoom(r.data as Room); if (r.data.round !== "lobby") setScreen("game"); } if (p.data) setPlayers(p.data as Player[]); if (e.data) setEvents((e.data as Event[]).reverse()); }; void load(); const channel = client.channel(`room-state-${room.id}`).on("postgres_changes", { event: "*", schema: "public", table: "rooms", filter: `id=eq.${room.id}` }, load).on("postgres_changes", { event: "*", schema: "public", table: "players", filter: `room_id=eq.${room.id}` }, load).on("postgres_changes", { event: "*", schema: "public", table: "game_events", filter: `room_id=eq.${room.id}` }, load).subscribe(); return () => { active = false; void client.removeChannel(channel); }; }, [room?.id]);
  const submit = async () => { setError(""); const n = name.trim(), c = code.trim().toUpperCase(); if (!n) return setError("Please enter your display name."); if (screen === "join" && !c) return setError("Please enter a room code."); if (!supabase) return setError("Supabase is not configured."); setBusy(true); try { let r: Room; if (screen === "create") { const newCode = `POWER-${Math.floor(10 + Math.random() * 90)}`; const x = await supabase.from("rooms").insert({ code: newCode }).select("id,code,host_player_id,round,current_player_id,last_roll").single(); if (x.error || !x.data) throw new Error(x.error?.message || "Could not create the room."); r = x.data as Room; } else { const x = await supabase.from("rooms").select("id,code,host_player_id,round,current_player_id,last_roll").eq("code", c).maybeSingle(); if (x.error || !x.data) throw new Error("That room does not exist. Check the code and try again."); r = x.data as Room; } if (r.round !== "lobby") throw new Error("This game has already started."); const x = await supabase.from("players").insert({ room_id: r.id, display_name: n }).select("id").single(); if (x.error || !x.data) throw new Error(x.error?.code === "23505" ? "That display name is already being used in this room." : x.error?.message || "Could not join the room."); if (screen === "create") { const h = await supabase.from("rooms").update({ host_player_id: x.data.id }).eq("id", r.id); if (h.error) throw new Error(h.error.message); r.host_player_id = x.data.id; } setRoom(r); setPlayer(x.data.id); setCode(r.code); setScreen("lobby"); history.replaceState({}, "", `/?room=${r.code}`); } catch (e) { setError(e instanceof Error ? e.message : "Something went wrong."); } finally { setBusy(false); } };
  const startGame = async () => { if (!supabase || !room || !player || room.round !== "lobby" || room.host_player_id !== player || players.length < 2) return; setBusy(true); setError(""); const { error: e } = await supabase.rpc("start_game", { p_room_id: room.id, p_player_id: player }); if (e) { console.error("Could not start the game:", e); setError("Could not start the game"); } setBusy(false); };
  const roll = async () => { if (!supabase || !room || !player) return; setBusy(true); setError(""); const { error: e } = await supabase.rpc("roll_round_1", { p_room_id: room.id, p_player_id: player }); if (e) setError(e.message); setBusy(false); };
  const current = useMemo(() => players.find(p => p.id === room?.current_player_id), [players, room?.current_player_id]); const me = players.find(p => p.id === player); const isMyTurn = room?.current_player_id === player; const isHost = Boolean(room?.host_player_id && player && players.some(p => p.id === player && p.id === room.host_player_id)); const canStart = Boolean(room && room.round === "lobby" && isHost && players.length >= 2);
  if (screen === "lobby" && room) return <main className="shell"><Header label="Live lobby" /><section className="lobby-card"><span className="eyebrow">Game room</span><h1>Waiting for players.</h1><p>Share the invite and get ready to roll.</p><div className="room-code"><span>ROOM CODE</span><strong>{room.code}</strong><button className="secondary" onClick={async () => { await navigator.clipboard.writeText(invite(room.code)); setCopied(true); setTimeout(() => setCopied(false), 1600); }}>{copied ? "Copied!" : "Copy invite link"}</button></div><div className="lobby-heading"><h2>Players <small>{players.length}</small></h2></div>{error && <div className="form-error">Could not start the game<div>{error}</div></div>}<div className="player-list">{players.map(p => <PlayerRow key={p.id} player={p} host={p.id === room.host_player_id} />)}</div><StartPanel isHost={isHost} playerCount={players.length} busy={busy} hasError={Boolean(error)} onStart={() => void startGame()} /></section></main>;
  if (screen === "game" && room) return <GameRoom room={room} players={players} events={events} me={me} current={current} isMyTurn={isMyTurn} busy={busy} error={error} roll={roll} />;
  if (screen !== "home") return <main className="shell"><Header /><section className="form-card"><span className="eyebrow">{screen === "create" ? "New game" : "Welcome back"}</span><h1>{screen === "create" ? "Create a room" : "Join a room"}</h1><p>{screen === "create" ? "Start a game and share the room code with your friends." : "Enter the room code your friend shared with you."}</p>{screen === "join" && <input value={code} onChange={e => setCode(e.target.value.toUpperCase())} placeholder="e.g. POWER-42" maxLength={8} />}<input value={name} onChange={e => setName(e.target.value)} placeholder="Your display name" maxLength={24} onKeyDown={e => { if (e.key === "Enter") void submit(); }} />{error && <div className="form-error">{error}</div>}<button className="primary wide" disabled={busy} onClick={() => void submit()}>{busy ? "Connecting…" : screen === "create" ? "Create room" : "Join room"}<span>→</span></button><button className="text-button" onClick={() => setScreen("home")}>Back to home</button></section></main>;
  return <Landing setScreen={setScreen} />;
}
function Header({ label = "Online multiplayer" }: { label?: string }) { return <div className="topbar"><div className="brand"><span className="brand-mark">✦</span> Power Ludo</div><div className="online-pill"><span /> {label}</div></div>; }
function PlayerRow({ player, host }: { player: Player; host: boolean }) { return <div className="player-row"><span className="player-avatar">{player.display_name[0].toUpperCase()}</span><strong>{player.display_name}</strong>{host && <span className="host-badge">HOST</span>}</div>; }
function StartPanel({ isHost, playerCount, busy, hasError, onStart }: { isHost: boolean; playerCount: number; busy: boolean; hasError: boolean; onStart: () => void }) {
  return <div className={`start-panel ${hasError ? "start-error" : ""}`}><div><span className="eyebrow">Game start</span><h3>{busy ? "Starting game..." : isHost ? playerCount >= 2 ? "Ready to play?" : "Waiting for players" : "Waiting for the host"}</h3><p>{busy ? "Moving everyone into Round 1." : isHost ? playerCount >= 2 ? "All players are in the room." : "Waiting for at least 2 players" : "Waiting for the host to start the game..."}</p></div>{isHost && <button className="primary start-button" disabled={busy || playerCount < 2} onClick={onStart}>{busy ? "Starting game..." : "START GAME"} <span>→</span></button>}</div>;
}
function GameRoom({ room, players, events, me, current, isMyTurn, busy, error, roll }: { room: Room; players: Player[]; events: Event[]; me?: Player; current?: Player; isMyTurn: boolean; busy: boolean; error: string; roll: () => Promise<void> }) { return <main className="shell"><Header label="Live game" /><section className="game-card"><div className="game-head"><div><span className="eyebrow">Room {room.code}</span><h1>{room.round === "round_1" ? "Round 1" : "Round 2"}</h1></div><div className="turn-pill"><span /> {current ? `${current.display_name}'s turn` : "Game ready"}</div></div><div className="game-grid"><div className="play-panel"><div className="dice-card game-dice"><div className="dice-face"><i/><i/><i/><i/><i/><i/></div><div className="dice-caption"><strong>{room.last_roll ?? "–"}</strong><span>{room.last_roll ? `${power(room.last_roll)} power` : "Last roll"}</span></div></div><button className="primary roll-button" disabled={room.round !== "round_1" || !isMyTurn || busy} onClick={() => void roll()}>{busy ? "Rolling…" : isMyTurn ? "Roll dice" : `Waiting for ${current?.display_name ?? "player"}`} <span>→</span></button><div className="your-score"><span>Your points</span><strong>{me?.points ?? 0}<small>/20</small></strong></div>{error && <div className="form-error">{error}</div>}</div><aside className="players-panel"><h2>Players <small>{players.length}</small></h2>{players.map(p => <div className={`score-row ${p.id === room.current_player_id ? "active" : ""}`} key={p.id}><span className="player-avatar">{p.display_name[0].toUpperCase()}</span><div><strong>{p.display_name}</strong><small>{p.status === "locked" ? "Locked" : "Unlocked"}</small></div><b>{p.points}</b></div>)}<h2 className="log-title">Game log</h2><div className="game-log">{events.map(e => <p key={e.id}>{e.message}</p>)}</div></aside></div></section></main>; }
function Landing({ setScreen }: { setScreen: (screen: Screen) => void }) { return <main className="shell home"><Header /><section className="hero"><div className="hero-copy"><span className="eyebrow">The strategy starts here</span><h1>Roll with power.<br/><em>Play to win.</em></h1><p>A fresh take on Ludo where every roll is a decision. Build your points, outplay your rivals, and be the last one standing.</p><div className="hero-actions"><button className="primary" onClick={() => setScreen("create")}>Create a room <span>→</span></button><button className="secondary" onClick={() => setScreen("join")}>Join a room</button></div></div><div className="dice-stage"><div className="glow"/><div className="dice-card"><div className="dice-face"><i/><i/><i/><i/><i/><i/></div><div className="dice-caption"><strong>6</strong><span>10 power</span></div></div><div className="float-chip chip-top">+10 <small>POWER</small></div><div className="float-chip chip-bottom">20 <small>MAX POINTS</small></div></div></section><section className="rules"><div><span className="eyebrow">Simple rules, deep play</span><h2>Every roll has a purpose.</h2></div><div className="rule-grid"><article><b>01</b><h3>Roll the dice</h3><p>Roll 1–6. Only 5 and 6 generate power.</p></article><article><b>02</b><h3>Spend wisely</h3><p>Build points, attack, or lock your opponents.</p></article><article><b>03</b><h3>Be the last</h3><p>Make the final successful lock to win.</p></article></div></section></main>; }
